import ApolloProviderComponent from "@/components/ApolloProviderComponent";
import FontAwesomeProvider from "@/components/FontAwesomeProviders";
import { SpeedInsights } from '@vercel/speed-insights/next';
import ReduxProvider from "@/components/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "ChatMoko | Messaging",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProviderComponent>
          <FontAwesomeProvider>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </FontAwesomeProvider>
        </ApolloProviderComponent>
        <SpeedInsights />
      </body>
    </html>
  );
}
