import type { Metadata } from "next";
import { Inter } from "next/font/google";
import FontAwesomeProvider from "@/components/FontAwesomeProviders";
import ApolloProviderComponent from "@/components/ApolloProviderComponent";
const inter = Inter({ subsets: ["latin"] });
import ReduxProvider from "@/components/ReduxProvider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";


export const metadata: Metadata = {
  title: "IDYOURS | Showcase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProviderComponent>
          <FontAwesomeProvider>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </FontAwesomeProvider>
        </ApolloProviderComponent>
      </body>
    </html>
  );
}
